### PR TITLE
changed en to en_core_web_sm

### PR DESCRIPTION
**Pull request by Ifyokoh**
Got the error 'can't find model 'en'' on importing datasist. On changing it to 'en_core_web_sm' it worked on the nlp.py file

### CODE REVIEW

**Comment by risenW** [comment]
This change failed the Travis CI test, It probably has to do with the environment you're working on. I'm suggesting we use the nltk module instead of spacy. And also adding it to the requirements.txt file. 
@tosi-n

**Comment by tosi-n** [comment]
@Ifyokoh You don't need to change the model, use the default english model. The reason for choosing that is because further abstraction nlp processes such as tokenisation and custom NER would be added to the NLP module soon which is only possible with the "en" model.

Going forward the documentation would be updated with sufficient information on required pre-requisites.

**Comment by risenW** [comment]
Are you still working on this? @tosi-n

**Comment by tosi-n** [comment]
Done, build failed initially because of model import error @risenW 
I also added the Readme update we spoke about.

Thank you @Ifyokoh for spotting the inability of "en" model working on Windows machine.

**Comment by risenW** [comment]
The proposed change didn't work, so the NLP module will be removed for now until we fix it.

**Pull request closed without merging**
