### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by Olaniyiajayi2**

### CODE REVIEW

**Comment by risenW** [comment]
Hello Olaniyi, thanks for taking out time to contribute to datasist, its really appreciated. 
The module you intend adding (bagging) already exist in scikit learn package, and there isn't any need to recrate it in datasist. 
The goal of datasist is to complement these existing libraries by abstracting repetitive codes. 

Cheers

**Comment by Emekaborisama** [comment]
🙌🏽🙌🏽🙌🏽🙌🏽

**Comment by Olaniyiajayi2** [comment]
Thank you risenW.

Although the module already exist in sklearn, some repetitive codes as still written In order to compare the performance of ordinary classifiers to the bagged classifier.... The contributed module (bagging) helps in abstracting this, where ordinary classifiers are provided as an array, and the function returns the performance of the ordinary classifier to the bagged equivalent. I plan to do same with boosting and stalking ensemble methods...... But if it's not the goal of Datasist still, I'd appreciate it if you can point out some areas where contributions are further need.

Cheers

**Comment by risenW** [comment]
Okay, I'll create some new issues and tag you right away.

**Pull request closed without merging**
